spring:
  application:
    name: config-server

  # git管理配置https://github.com/mingwulipo/config-repertory.git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mingwulipo/cloud-demo.git
          username: mingwulipo
          password: github8278784
          label: master
          #仓库路径
          searchPaths: config-repertory
          #加载到本地目录
          basedir: ./config-repo:

server:
  port: 9050

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

